module.exports = {
  USER_NOT_FOUND: 'User not found',
  USER_IS_EXISTS: 'User already exists',
  FARM_NOT_FOUND: 'Farm not found',
  FARM_UPDATE_ERROR: 'Farm update error',
  CATEGORY_NOT_FOUND: 'Category not found',
  CATEGORY_IS_EXISTS: 'Category already exists',
  COMMODITY_NOT_FOUND: 'Commodity not found',
  MARKET_NOT_FOUND: 'Market not found',
  WORKER_REGISTRATION_NOT_FOUND: 'Token is not valid',
  WORKER_REGISTRATION_IS_AT_DURATION: 'Token already generated, please wait',
  WORKER_ALREADY_REGISTERED: 'Worker already registered',
  WORKER_TASK_NOT_FOUND: 'Worker task is not found',
  WORKER_TASK_DONE: 'Worker task is already done',
  WORKER_PERMIT_NOT_FOUND: 'Worker permit is not found',
};
